project:
  type: website
  output-dir: docs
  preview:
    port: 6459
    browser: false
    watch-inputs: true
    navigate: true

website:
  title: "josephbarraud.dev"
  site-url: https://josephbarraud.dev
  favicon: rockall_bathy_64x64.png
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jobar8
        rel: me
      - icon: linkedin
        href: https://www.linkedin.com/in/josephbarraud

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true

author:
  - name: Dr Joseph Barraud
